c_price= int(input("Entert a cost price"))
s_price= int(input("Entert a sell price"))
profit =(s_price-c_price)
print(f"profit = {profit}")
print(f"seeling price should be :{s_price+profit*(5/100)} for 5 % more profit")
